### ISSUE TITLE
개발 환경 세팅

### ISSUE THREAD

**Issue by nijesmik** [KAGGU/frontend#2]
# 기술스택
- Next.js
- CSS
  - Server Component : Tailwind CSS + SCSS
    - [reference](https://tailwindcss.com/docs/functions-and-directives)
  - Client Component : 

---

### To-do
- [x] Sass 설치
- [x] prettier 설치 및 `.prettierrc` 설정
- [x] `.eslintrc` 설정
- [x] 상태관리 라이브러리 ex) jotai
- [x] 클라이언트 컴포넌트 CSS
- [x] mui vs [daisyui](https://daisyui.com) vs [flowbite](https://flowbite.com)
